kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v1alpha2
storageConfig:
  local:
    path: ./content
mirror:
  platform:
    channels:
    - name: stable-4.15
      type: ocp
      shortestPath: true
    - name: stable-4.14
      type: ocp
      shortestPath: true
    - name: stable-4.13
      type: ocp
      minVersion: 4.12.24
      shortestPath: true
    graph: true
