kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v1alpha2
storageConfig:
  local:
    path: ./
mirror:
  platform:
    channels:
    - name: stable-4.15
      type: ocp
      shortestPath: true
    graph: true
  operators:
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.16
    packages:
    - name: ansible-automation-platform-operator
    - name: cincinnati-operator
    - name: openshift-gitops-operator
    - name: advanced-cluster-management
    - name: quay-operator
    - name: container-security-operator
  - catalog: registry.redhat.io/redhat/certified-operator-index:v4.16
    packages:
    - name: elasticsearch-eck-operator-certified
  additionalImages:
  # List retrieved from tridentctl, installed from https://github.com/NetApp/trident
    # Used for NetApp storage CSI driver
  - name: docker.io/netapp/trident-operator:24.02.0
  - name: docker.io/netapp/trident:24.02.0
  - name: docker.io/netapp/trident-autosupport:24.02
  - name: registry.k8s.io/sig-storage/csi-provisioner:v4.0.0
  - name: registry.k8s.io/sig-storage/csi-attacher:v4.5.0
  - name: registry.k8s.io/sig-storage/csi-resizer:v1.9.3
  - name: registry.k8s.io/sig-storage/csi-snapshotter:v6.3.3
  - name: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.10.0
  - name: registry.access.redhat.com/ubi9/httpd-24:1-325
  helm:
    repositories:
      - name: netapp-trident
        url: https://netapp.github.io/trident-helm-chart
        charts:
          - name: trident-operator
            version: 100.2402.0
