kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v1alpha2
storageConfig:
  local:
    path: ./
mirror:
  platform:
    channels:
    - name: stable-4.15
      type: ocp
      shortestPath: true
    graph: true
  operators:
  - catalog: registry.redhat.io/redhat/redhat-operator-index:v4.16
    packages:
    - name: ansible-automation-platform-operator
    - name: cincinnati-operator
    - name: openshift-gitops-operator
    - name: advanced-cluster-management
    - name: devspaces
    - name: devworkspace-operator
    - name: elasticsearch-operator
    - name: kubevirt-hyperconverged
    - name: kubevirt-hyperconverged
    - name: openshift-cert-manager-operator
    - name: openshift-gitops-operator
    - name: openshift-pipelines-operator-rh
    - name: quay-operator
    - name: rhbk-operator
    - name: rhdh
    - name: rhods-operator
    - name: rhsso-operator
    - name: Red Hat OpenShift Service Mesh
  - catalog: registry.redhat.io/redhat/certified-operator-index:v4.16
    packages:
    - name: elasticsearch-eck-operator-certified
    - name: cilium
    - name: mongodb-enterprise
    - name: openshiftartifactoryha-operator
    - name: openshiftxray-operator
    - name: redis-enterprise-operator-cert
  - catalog: registry.redhat.io/redhat/community-operator-index:v4.16
    - name: argocd-operator
    - name: cert-manager
    - name: keycloak-operator
    - name: mongodb-operator
    - name: project-quay
    - name: redis-operator
    - name: vault-config-operator
  - catalog: registry.redhat.io/redhat/redhat-marketplace-index:v4.16
    - name: redis-enterprise-operator-cert-rhmp
  additionalImages:
  # List retrieved from tridentctl, installed from https://github.com/NetApp/trident
    # Used for NetApp storage CSI driver
  - name: docker.io/netapp/trident-operator:24.02.0
  - name: docker.io/netapp/trident:24.02.0
  - name: docker.io/netapp/trident-autosupport:24.02
  - name: registry.k8s.io/sig-storage/csi-provisioner:v4.0.0
  - name: registry.k8s.io/sig-storage/csi-attacher:v4.5.0
  - name: registry.k8s.io/sig-storage/csi-resizer:v1.9.3
  - name: registry.k8s.io/sig-storage/csi-snapshotter:v6.3.3
  - name: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.10.0
  - name: registry.redhat.io/rhel8/nginx-124:1-12.1717586547
  - name: registry.access.redhat.com/ubi8/nginx-124:1-12.1717586547
  - name: registry.redhat.io/rhel8/postgresql-12:1-168.1717586541
  - name: registry.redhat.io/rhel8/postgresql-13:1-185.1717586543
  - name: registry.redhat.io/rhel8/postgresql-15:1-66.1717586531
  helm:
    repositories:
      - name: netapp-trident
        url: https://netapp.github.io/trident-helm-chart
        charts:
          - name: trident-operator
            version: 100.2402.0
