kind: ImageSetConfiguration
apiVersion: mirror.openshift.io/v1alpha2
storageConfig:
  local:
    path: ./
mirror:
  additionalImages:
  # List retrieved from tridentctl, installed from https://github.com/NetApp/trident
    # Used for NetApp storage CSI driver
  - name: docker.io/netapp/trident:24.02.0
  - name: docker.io/netapp/trident-autosupport:24.02
  - name: registry.k8s.io/sig-storage/csi-provisioner:v4.0.0
  - name: registry.k8s.io/sig-storage/csi-attacher:v4.5.0
  - name: registry.k8s.io/sig-storage/csi-resizer:v1.9.3
  - name: registry.k8s.io/sig-storage/csi-snapshotter:v6.3.3
  - name: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.10.0
  - name: docker.io/netapp/trident-operator:24.02.0
  # https://docs.openshift.com/container-platform/4.15/installing/disconnected_install/installing-mirroring-disconnected.html#oc-mirror-image-set-examples_installing-mirroring-disconnected
  helm:
    repositories:
    - name: netapp-trident
      url: https://netapp.github.io/trident-helm-chart
      charts:
      - name: trident-operator
        version: 100.2402.0

